name:                WHILE
version:             0.1.0.0
github:              "thuytien140894/CMPS203/tree/WHILE"
license:             BSD3
author:              "Tien Thuy Ho"
maintainer:          "example@example.com"
copyright:           "2018 Tien Thuy Ho"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/thuytien140894/CMPS203/tree/WHILE/#readme>

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 3.0
- containers >= 0.5 && < 0.6

library:
  source-dirs: src

executables:
  Tien-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WHILE

tests:
  Tien-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WHILE
    - base >=4.7 && <5
    - hspec >= 2.2
    - containers >= 0.5 && < 0.6
